export const SEARCH_START = 'SEARCH_START'; 

export const FETCH_VIDEOS = 'FETCH_VIDEOS'; 
export const FETCH_VIDEOS_START = 'FETCH_VIDEOS_START'; 
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS'; 
export const FETCH_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL'; 

export const SELECT_VIDEO = 'SELECT_VIDEO'; 
export const SELECT_VIDEO_SUCCESS = 'SELECT_VIDEO_SUCCESS'; 
export const EXTEND_DETAIL = 'EXTEND_DETAIL';

export const FETCH_CHANEEL = 'FETCH_CHANEEL';
export const FETCH_CHANEEL_START = 'FETCH_CHANEEL_START';
export const FETCH_CHANEEL_SUCCESS = 'FETCH_CHANEEL_SUCCESS';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const SWITCH_SORT_BOX = 'SWITCH_SORT_BOX';
export const CLOSE_SORT_BOX = 'CLOSE_SORT_BOX';
export const IN_SORT_BOX = 'IN_SORT_BOX';
export const OUT_SORT_BOX = 'OUT_SORT_BOX';
export const SET_COMMENTS_ORDER = 'SET_COMMENTS_ORDER'; 
export const FETCH_COMMENTS_ORDER_START = 'FETCH_COMMENTS_ORDER_START';
export const FETCH_COMMENTS_ORDER_SUCCESS = 'FETCH_COMMENTS_ORDER_SUCCESS';